name: exabyte
description: Am app for eXabyte 2020.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+4

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^1.3.0
  font_awesome_flutter: ^8.5.0
  kf_drawer: ^1.1.2
  provider: ^4.0.1
  url_launcher: ^5.4.1
  share: ^0.6.3+5
  shared_preferences: ^0.5.6+1
  cloud_firestore: ^0.13.2+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: true 
  ios: true
  image_path: "assets/images/Asset3.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/Asset2.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/codeplay.jpeg
   - assets/images/crosshair.jpeg
   - assets/images/cryptx.jpeg
   - assets/images/cubex.jpeg
   - assets/images/debate.jpeg
   - assets/images/embleed.jpeg
   - assets/images/digibit.jpeg
   - assets/images/snappit.jpeg
   - assets/images/pitch.jpeg
  #  - assets/images/robolt.jpg
   - assets/images/fifa.jpg
   - assets/images/robolt.jpg
   - assets/images/quiz.jpeg
   - assets/images/webbed.jpeg
   - assets/images/profile.jpeg
   - assets/images/palit.jpg
   - assets/images/rush.jpg
   - assets/images/shreya.jpg
   - assets/images/sirshu.jpg
   - assets/images/ashok.jpg
   - assets/images/audi.JPG
   - assets/images/code.jpg
   - assets/images/deb.jpg
   - assets/images/sa.JPG
   - assets/images/stage.JPG
   - assets/images/Asset2.png
   
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
    - family: Caviar Dreams
      fonts:
        - asset: assets/fonts/CaviarDreams.ttf
        - asset: assets/fonts/CaviarDreams_Bold.ttf
          weight: 700
        - asset: assets/fonts/CaviarDreams_Italic.ttf
          style: italic
    - family: Ubuntu Mono
      fonts: 
        - asset: assets/fonts/UbuntuMono-Regular.ttf
        - asset: assets/fonts/UbuntuMono-Bold.ttf
          weight: 700
    - family: Product Sans
      fonts: 
        - asset: assets/fonts/Product-Sans-Regular.ttf
        - asset: assets/fonts/Product-Sans-Bold.ttf
          weight: 700
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/DancingScript.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
